Major changes in code.
Some changes to the help message output, added a `-c` and `-v` flags, changes in `gen-appimage` script and implemented the 3rd build method for Arch-based Linux distributions (2nd still hasn't been implemented yet). There're probably some other minior changes, too.

diff --git a/package b/package
--- a/package
+++ b/package
@@ -29,87 +29,132 @@ PLATFORM_LIST=('Raspberry Pi (2/3/4)' 'RK3399' 'ODROID' 'Gameshell' 'Pandora' 'P
 LIB_MODE_ARR=('Copy all files.' 'Copy ".so" libraries.'
               'Copy only necessary libraries.')
 AL_LIB_REQUIRED=('glibc' 'gcc-libs')
+SCRIPT_NAME="`basename "$(git -C "${HERE}" remote -v | head -n1 | awk '{print $2}')" .git`-`basename $0 .sh`"
+[[ "$(date +%Y)" == "2021" ]] && CP_YEAR="2021" || CP_YEAR="2021-$(date %Y)"
 
 # GOTO: External scripts
 hash -p "${HERE}/tools/gen-appimage.sh" gen-appimage
 
+# Functions for easier text formatting:
+
+help_tl(){
+    echo -e "\n\e[1;4m${@}\e[0m"
+}
+help_dc(){
+    printf '%-36.36s\e[2m%-.38s\e[0m\n' "`printf "$1"`" "`printf "${@:2}"`"
+}
+help_nx(){
+    printf '\e[2m%-36.36s%s\e[0m\n' ' ' "${@}"
+}
+help_dc2(){
+    printf "%-55.55s\e[2m%s\e[0m\n" "$(printf "\033[1;94m->\033[0m \033[1m${1}=\033[0m${2}")" "${3}"
+}
+
 # Functions:
+get_ver(){
+    printf "r%s.%s" "$(git -C "${HERE}" rev-list --count HEAD)" "$(git -C "${HERE}" rev-parse --short HEAD)"
+}
+
+version(){
+    echo -e "\n${SCRIPT_NAME}, version $(get_ver)"
+    echo -e "\nCopyright (C) ${CP_YEAR} SpacingBat3\n"
+    echo "This program comes with ABSOLUTELY NO WARRANTY."
+    echo "This is free software, and you are welcome to redistribute it"
+    echo -e "under certain conditions.\n"
+}
+
 chroot(){
     sudo -p "[chroot] Enter your password: " "${HERE}/tools/chroot.sh" \
-    "${CHROOT_DIR}" "${HERE}" "${UID}" "$@"
+    "${CHROOT_DIR}" "${HERE}/src/box86" "${UID}" "${USER}" "$@"
 }
 
 help(){
-    y="$((${#LIB_MODE_ARR[@]}-1))"; x="[0-${x:0:21}]"
-    printf -v x %-21.21s "$x"
+    x="$((${#LIB_MODE_ARR[@]}-1))"
     usage
-    echo -e "\n\e[1;4mVARIABLES:\e[0m"
-    echo -e " \e[1;94m->\e[0m \e[1mARCH=\e[0m[aarch64/armv7(l/h)]         \e[2mBOX86 target CPU architecture\e[0m"
-    echo -e "                                      \e[2m(default: host arch = `uname -m`).\e[0m"
-    echo -e " \e[1;94m->\e[0m \e[1mBUILD_PLATFORM=\e[0m[PLATFORM]         \e[2mOverwrites PLATFORM to optimize the\e[0m"
-    echo -e "                                      \e[2mbuild for (default: host).\e[0m"
-    echo -e " \e[1;94m->\e[0m \e[1mCHROOT_DIR=\e[0m[PATH]                 \e[2mSets the ARMHF chroot path which will\e[0m"
-    echo -e "                                      \e[2mbe used to compile box86 on AARCH64\e[0m"
-    echo -e "                                      \e[2mhost.\e[0m"
-    echo -e " \e[1;94m->\e[0m \e[1mCP_LIB_MODE=\e[0m${x} \e[2mSets the mode of filtering libraries.\e[0m"
-    echo -e " \e[1;94m->\e[0m \e[1mRESET=\e[0m[STEP]                      \e[2mRestart the build from this STEP.\e[0m"
+    help_tl "VARIABLES:"
+    help_dc2 "ARCH" "[aarch64/armv7(l/h)]" "BOX86 target CPU architecture"
+    help_nx "(default: host arch = `uname -m`)"
+    help_dc2 "BUILD_PLATFORM" "[PLATFORM]" "Overwrites PLATFORM to optimize the"
+    help_nx "build for (default: host = ${platform})."
+    help_dc2 "CHROOT_DIR" "[PATH]" "Sets the ARMHF chroot path which will"
+    help_nx "be used to compile box86 on AARCH64"
+    help_nx "host."
+    help_dc2 "CP_LIB_MODE" "[0-${x}]" "Sets the mode of filtering libraries."
+    help_dc2 "RESET" "[STEP]" "Restart the build from this STEP."
     echo
     echo "You can also prefix the variable name with the \"BOX86_APPIMAGE_\" if you want"
     echo "to save it as an enviroment variable and you are aware the regural variable"
     echo "names will be in conflict with variables used by the other software." 
-    echo -e "\n\e[1;4mPLATFORMS:\e[0m"
+    help_tl "PLATFORMS:"
     printf -v PLATFORM_ALL '%s, ' "${PLATFORM_LIST[@]}"
     echo -e " \e[1;92m✓\e[0m ${PLATFORM_ALL%, }"
     echo
     x=0
-    echo -e "\e[1;4mLIBRARY FILTERS:\e[0m"
+    help_tl "LIBRARY FILTERS:"
     until [[ "$x" -gt "$[${#LIB_MODE_ARR[@]}-1]" ]]; do
         printf " \e[1m%s\e[0m = %s\n" "$x" "${LIB_MODE_ARR[$x]}"
         let x++
     done
     echo -e "\nThese values also indidicates the disk space usage by the libraries inside"
-    echo "the AppImage – where 0 indicates the lowest disk space usage and ${y} – the"
-    echo "highest."
+    echo "the AppImage – where 0 indicates the highest disk space usage and ${x} – the"
+    echo "lowest."
     echo -e "\nPlease note that this variable shouldn't be set to the highest value unless"
     echo "you want to provide the libraries by yourself outside the AppImage (which"
     echo "generally takes more disk space because AppImages are compressed) or you"
     echo "would like to use the Appimage as a dependency to package X86 binary on"
-    echo "AARCH64 distributables."
+    echo "AArch64 distributables."
     echo
 }
 
 usage(){
     echo -e "\n\e[1mUSAGE\e[0m: `basename $0` [FOO=BAR]..."
-    echo -e "\n\e[1;4mARGUMENTS:\e[0m"
-    echo -e " -h   --help                          \e[2mDisplay entire help message.\e[0m"
-    echo -e " -u   --usage                         \e[2mDisplay script usage.\e[0m"
+    help_tl "ARGUMENTS:"
+    help_dc " -h   --help" "Display entire help message."
+    help_dc " -u   --usage" "Display script usage."
+    help_dc " -c   --clear" "Clear build files to free some disk space."
 }
 
 error(){
-    echo; printf "\nERROR: "
+    [[ "$1" != 130 ]] && sleep 3s
+    clear; tput rmcup
+    trap - EXIT
+    printf "\nERROR: "
     case "$1" in
         1)  echo "Build method: \"${build_method}\" not implemented yet!"           ;;
         2)  echo "GIT was not installed!"                                           ;;
         3)  echo "Unsupported linux distrinution!"                                  ;;
         4)  echo "Unsupported Raspberry Pi device!"                                 ;;
-        5)  echo "Missing dependency: ${dependends}!"                               ;;
+        5)  echo "Missing dependency: ${depends}!"                                  ;;
         6)  echo "Source file/directory not found!"                                 ;;
         7)  echo "Couldn't get all sources!"                                        ;;
         8)  echo "Unsupported architecture ${ARCH}!"                                ;;
         9)  echo "An error occured while ${2}!"                                     ;;
         10) echo "Unimplemented selection!"                                         ;;
+        11) echo "Couldn't make the chroot enviroment!"                             ;;
+        12) echo "Directory \"${2}\" already exists!"                               ;;
+        130) echo "Received INT signal!"                                            ;;
         *) 
             echo "Unknown error!"
             echo "Exit code ${1}!"
         ;;
     esac
+    stty echo >/dev/null 2>&1
     echo; exit "$1"
 }
 
 workdirs(){
-    [[ ! -d "${HERE}/src" ]] && mkdir "${HERE}/src"
-    [[ -f "${HERE}/build/CMakeCache.txt" ]] && rm -f "${HERE}/build/CMakeCache.txt"
-    [[ -d "${HERE}/final.AppDir" ]] && rm -Rf "${HERE}/final.AppDir" >/dev/null 2>&1
+    case "${argv[@]}" in
+    -*c*|"--clear")
+        cleanup_all
+    ;;&
+    *)
+        printf "\nPreparing the script's work directory..."
+        [[ ! -d "${HERE}/src" ]] && mkdir "${HERE}/src"
+        [[ -f "${HERE}/src/box86/build/CMakeCache.txt" ]] && rm -f "${HERE}/box86/build/CMakeCache.txt"
+        [[ -d "${HERE}/final.AppDir" ]] && rm -Rf "${HERE}/final.AppDir" >/dev/null 2>&1
+        echo " Done!"
+    ;;
+    esac
 }
 
 cleanup() {
@@ -120,7 +165,12 @@ cleanup() {
 }
 
 cleanup_all(){
-    printf "\n"
+    printf "\nRemoving build files..."
+    readarray -t temp_dirs <"${HERE}/.gitignore"
+    for dir in "${temp_dirs[@]}"; do
+        [[ -d "$dir" ]] && rm -Rf "${HERE}/${dir}" 
+    done
+    echo " Done!"
 }
 
 get_sources(){
@@ -130,6 +180,7 @@ get_sources(){
         git -C "${HERE}/src/box86" pull origin master >/dev/null 2>&1
         error="$?"; [[ "$error" == 0 ]] && echo -e " Done!\n" || error 7
     else
+        printf "\nCloning the box86 GIT repository..."
         mkdir "${HERE}/src/box86"
         git clone "${GIT_REPO}" "${HERE}/src/box86" >/dev/null 2>&1
         error="$?"; [[ "$error" == 0 ]] && echo -e " Done!\n" || error 7
@@ -171,21 +222,33 @@ package_appimage_32(){
     echo
 }
 
-create_chroot(){
-    # TODO: A script to create an chroot enviroment on the Arch Linux.
-    [[ -f /etc/pacman.conf && -f /etc/makepkg.conf ]] || error 3    
+make_chroot(){
+     check_dependencies mkarchroot pacman
+     [[ -d "${HERE}/src/chroot" ]] && error 12 "src/chroot"
+     echo "Please enter additional packages to install to the chroot enviroment."
+     echo "You can leave this field empty if you want to use the defaults only."
+     read -p "Pacman package list: (base-devel cmake python) " CHROOT_PACKAGES
+     stty -echo >/dev/null 2>&1
+     mkarchroot -sC "${HERE}/tools/pacman.conf" "${HERE}/src/chroot" base-devel cmake python ${CHROOT_PACKAGES} \
+     || (stty echo >/dev/null 2>&1; sudo env HERE="${HERE}" PKG="CHROOT_PACKAGES" \
+        bash -c 'stty -echo >/dev/null 2>&1; pacman  -Syr "${HERE}/src/chroot" \
+        --config "${HERE}/tools/pacman.conf" base-devel cmake python ${PKG}') \
+     || error 11
+     [[ -d "${HERE}/src/chroot" ]] && CHROOT_DIR="${HERE}/src/chroot"
 }
 
 build_chroot(){
+    [[ -z "${CHROOT_DIR}" && -f "${HERE}/src/chroot/lib/ld-linux-armhf.so.3" ]] && \
+        CHROOT_DIR="${HERE}/src/chroot/" && \
+        echo "Found ARMHF chroot: \"${CHROOT_DIR}\"!"
     if [[ -z "$CHROOT_DIR" ]]; then
         until [[ ! -z "$LOOP_END" && "$LOOP_END" != 0 ]]; do
             read -ep 'Enter the "armv7h" chroot path: ' CHROOT_DIR
             if [[ ! -d "$CHROOT_DIR" ]]; then
                 echo "$CHROOT_DIR isn't a directory!"
                 echo "Please type the correct path to the directory."
-            elif [[ ! -d "$CHROOT_DIR/bin" && ! -d "$CHROOT_DIR/lib" ]] && \
-                 [[ ! -d "$CHROOT_DIR/usr" && ! -d "$CHROOT_DIR/var" ]]; then
-                echo "$CHROOT_DIR isn't the root folder!"
+            elif [[ ! -f "$CHROOT/lib/ld-linux-armhf.so.3" ]]; then
+                echo "$CHROOT_DIR has no ARMHF linker!"
             else
                 LOOP_END=1
             fi
@@ -197,9 +260,9 @@ build_chroot(){
     INT32="${CHROOT_DIR}/lib/ld-linux-armhf.so.3"
     check_dependencies --chroot make cmake gcc g++
     flags="${cmake_flags[@]}" chroot /usr/bin/bash -c \
-        'cd /mnt/; mkdir build >/dev/null 2>&1; cd build; \
-        cmake "../src/box86" $flags -DCMAKE_BUILD_TYPE=RelWithDebInfo; \
-        make -j$(nproc)'
+        'stty -echo >/dev/null 2>&1; cd /mnt; mkdir build >/dev/null 2>&1; \
+        cd build; cmake .. $flags -DCMAKE_BUILD_TYPE=RelWithDebInfo; \
+        make -j$(nproc); stty echo >/dev/null 2>&1'
     PACKAGE_MODE=0
 }
 
@@ -209,13 +272,13 @@ build_toolchain(){
 }
 
 check_dependencies(){
-    if [[ "$1" =~ "chroot" ]]; then
+    if [[ "$1" == "--chroot" ]]; then
         for depends in "${@:2}"; do
             [[ -f "${BIN32}/${depends}" ]] || error 5
         done
     else
         for depends in "${@}"; do
-            which "$depends" >/dev/null 2>&1 || error 5
+            which "$depends" >> /dev/null 2>&1 || error 5
         done
     fi
 }
@@ -224,9 +287,9 @@ install_box86(){
     case "$PACKAGE_MODE" in
         0)
             pkgdir="${HERE}/final.AppDir/usr"
-            install -Dm755 "${HERE}/build/box86" "${pkgdir}/bin/box86"
+            install -Dm755 "${HERE}/src/box86/build/box86" "${pkgdir}/bin/box86"
             [[ ! -d "${pkgdir}/lib/i386-linux-gnu" ]] && mkdir -p "${pkgdir}/lib/i386-linux-gnu"
-            cp -Rpt "${pkgdir}/lib/i386-linux-gnu" "${HERE}/src/box86/x86lib/"*
+            cp -Rdt "${pkgdir}/lib/i386-linux-gnu" "${HERE}/src/box86/x86lib/"*
             chmod 755 "${pkgdir}/lib/i386-linux-gnu"
             chmod -R 644 "${pkgdir}/lib/i386-linux-gnu/"*
             install -Dm644 "${HERE}/src/box86/LICENSE" "${pkgdir}/share/licenses/box86/LICENSE"
@@ -241,32 +304,34 @@ install_libs(){
         if [[ "$CP_LIB_MODE" > 0 ]] && [[ "$CP_LIB_MODE" < "${#LIB_MODE_ARR[@]}" ]] && [ "$CP_LIB_MODE" -eq "$CP_LIB_MODE" ] 2>/dev/null ; then
             lib_mode="${LIB_MODE_ARR[$CP_LIB_MODE]}"
         else
-            echo "Select mode: "
+            echo -e "\n\e[1mSelect the method on which libraries are copied:\e[0m "
             select lib_mode in "${LIB_MODE_ARR[@]}"; do
                 [[ ! -z $lib_mode ]] && break
             done
         fi
+        
+        stty -echo >/dev/null 2>&1
         printf "\nCopying the \`/lib\` content from the current chroot..."
         [[ ! -d "${HERE}/final.AppDir/usr/lib/" ]] && mkdir -p "${HERE}/final.AppDir/usr/lib/"
         case "$lib_mode" in
-            *'all files'*)
-                sudo cp -at "${HERE}/final.AppDir/usr/lib/" "${CHROOT_DIR}/usr/lib/"*
+            *'all'*)
+                cp -dt "${HERE}/final.AppDir/usr/lib/" "${CHROOT_DIR}/usr/lib/"* >/dev/null 2>&1
                 error="$?"
             ;;
-            *'".so" files'*)
+            *'".so"'*)
                 cd "${CHROOT_DIR}/usr/lib/"
-                readarray -d '' LIB_FILES < <(sudo find * ! -type d -name '*.so' -print0 -o ! -type d -name '*.so.*' -print0)
+                readarray -d '' LIB_FILES < <(find * ! -type d -name '*.so' -print0 -o ! -type d -name '*.so.*' -print0)
                 for file in "${LIB_FILES[@]}"; do
-                    sudo cp --parents -at "${HERE}/final.AppDir/usr/lib/" "${file}"
+                    cp --parents -dt "${HERE}/final.AppDir/usr/lib/" "${file}"
                 done
                 error="$?"
                 cd "${OLD_WORKDIR}"
             ;;
-            *'necessary lib'*)
+            *'necessary'*)
                 #FIXME: Debian CHROOT support (and probably others too):
                 if [[ -f /etc/pacman.conf && -f "${CHROOT_32}/etc/pacman.conf" ]]; then
-                    readarray LIB_FILES < <(pacman -Qlr  "$CHROOT_DIR" "${AL_LIB_REQUIRED[@]}" | awk '{print $2}' | grep usr/lib | sed "s.$CHROOT_DIR/usr/lib/..g")
-                elif [[ -f "${CHROOT_32}/etc/pacman.conf" ]]; then
+                    readarray LIB_FILES < <(pacman -Qlr  "$CHROOT_DIR" "${AL_LIB_REQUIRED[@]}" | awk '{print $2}' | grep usr/lib | sed "s~$CHROOT_DIR/usr/lib/~~g")
+                elif [[ -f "${CHROOT_DIR}/etc/pacman.conf" ]]; then
                     readarray LIB_FILES < <(chroot env LIBS=("${AL_LIB_REQUIRED[@]}") /usr/bin/bash -c 'pacman -Ql "${LIBS[@]}" | awk {print\ \$2} | grep usr/lib | sed s./usr/lib/..g ' )
                 else
                     error 3
@@ -275,15 +340,17 @@ install_libs(){
                 for file in "${LIB_FILES[@]}"; do
                     file="$(tr -d '\n' <<<"${file}")"
                     if [[ -f "$file"  ]] && [[ "$file" == *'.so' || "$file" == *'.so.'* ]]; then
-                        sudo cp --parents -at "${HERE}/final.AppDir/usr/lib/" "${file}"
+                        cp -dt "${HERE}/final.AppDir/usr/lib/" "${file}"
                     fi
                 done
                 error="$?"
             ;;
             *) error 10 ;;
         esac
+        stty echo >/dev/null 2>&1
         [[ "$error" == 0 ]] && echo -e " Done!\n" || error 9 "copying libraries from the current chroot"
-        sudo -p "[chown] Enter your password: " chown -R "$ID" "${HERE}/final.AppDir/usr/lib/"
+        stty echo >/dev/null 2>&1
+        #sudo -p "[chown] Enter your password: " chown -R "$ID" "${HERE}/final.AppDir/usr/lib/"
         find "${HERE}/final.AppDir/usr/lib/" -xtype l -delete
     ;;
     1)
@@ -307,6 +374,7 @@ for var in ${@}; do
     case "$var" in
     -*h*|--"help") help; exit 0 ;;
     -*u*|"--usage") usage; echo; exit 0 ;;
+    -*v*|"--version") version; exit 0 ;;
     *?*"="*) declare "${var}" ;;
     *) argv+=("$var") ;;
     esac
@@ -322,9 +390,12 @@ RESET="${APPIMAGE_RESET:-${BOX86_APPIMAGE_RESET}}"
 # FIXME: Currently there's no support for the 32-bit build type.
 
 # Main part of the script
+tput smcup; clear
 get_device_info
+trap 'sleep 3s; clear; tput rmcup' EXIT
+trap 'error 130' INT
 PS3_DEFAULT="$PS3"
-PS3="Enter number: "
+PS3="$(printf '\033[1mEnter number:\033[0m') "
 if [[ ! -z "$RESET" ]]; then
     case "$RESET" in
         *"package"*) package_appimage; ARCH="$ARCH" gen-appimage "${HERE}/box86.AppDir" "${HERE}/dist/box86-${ARCH}-${platform}.AppImage" ;;
@@ -332,27 +403,28 @@ if [[ ! -z "$RESET" ]]; then
     exit 0
 fi
 if [[ "$(uname -m)" == "aarch64" ]]; then
-    echo "Which method will you use to build the BOX86 with on the `uname -m` host?"
-    select build_method in "with chroot" "with toolchain" "create new chroot"; do
-        if [[ ! -z "$build_method" ]]; then
-            check_dependencies 'git' 'arch-chroot'
-            workdirs; get_sources
-            echo "Platform: \"$(printf "${platform}" | tr a-z A-Z )\"."
-            echo -e "CMAKE flags: ${cmake_flags[@]}\n"
-            case "$build_method" in 
-                "with chroot") build_chroot ;;
-                #"with toolchain") build_toolchain ;;
-                #"create new chroot") create_chroot; build_chroot ;;
-                *) error 1 ;;
-            esac
-            install_box86;
-            [[ "$ARCH" == "aarch64" ]] && install_libs
-            package_appimage; ARCH="$ARCH" gen-appimage "${HERE}/box86.AppDir" "${HERE}/dist/box86-${ARCH}-${platform}.AppImage"
-            cleanup
-            break
-        fi
+    echo -e "\e[1mWith which method would you like to use to build the BOX86 on the `uname -m` host?\e[0m"
+    select build_method in "chroot enviroment" "toolchain" "new chroot enviroment"; do
+        [[ ! -z "$build_method" ]] && break
     done
-elif [[ "$(uname -m)" == "armv7h" || "$(uname -m)" == "armv7l" ]]; then
+    if [[ ! -z "$build_method" ]]; then
+        check_dependencies 'git' 'arch-chroot'
+        workdirs; get_sources
+        echo "Platform: \"$(tr a-z A-Z <<<"${platform}")\"."
+        echo -e "CMAKE flags: ${cmake_flags[@]}\n"
+        case "$build_method" in 
+            "chroot"*) build_chroot ;;
+            #"toolchain"*) build_toolchain ;;
+            "new chroot"*) make_chroot; build_chroot ;;
+            *) error 1 ;;
+        esac
+        install_box86;
+        [[ "$ARCH" == "aarch64" ]] && install_libs
+        package_appimage; ARCH="$ARCH" gen-appimage "${HERE}/box86.AppDir" "${HERE}/dist/box86-${ARCH}-${platform}.AppImage"
+        error="$?"; [[ "$error" == 0 ]] || error 9 "packaging the box86"
+        cleanup
+    fi
+elif [[ "$(uname -m)" =~ "armv7" || "$(uname -m)" == "armhf" || "$(uname -m)" == "arm32" ]]; then
     # TODO: Package on the ARMv7 hosts.
     error 8
 else
@@ -361,4 +433,7 @@ fi
 PS3="$PS3_DEFAULT"
 unset PS3_DEFAULT
 hash -r
+trap - EXIT INT
+tput rmcup
+echo -e "\nSuccessfully packaged the Appmage!\n"
 exit 0
